### ISSUE TITLE
Alacritty Support

### ISSUE THREAD

**Issue by NOTtheMessiah** [stayradiated/termcolors#8]
[Alacritty](https://github.com/jwilm/alacritty) is a terminal emulator with GPU acceleration currently under development. Configuration is very simple, just a [YAML file](https://github.com/jwilm/alacritty/blob/master/alacritty.yml).

**Comment by stayradiated** [comment]
I'm actually using Alacritty at the moment. I should totally add this.

**Comment by stayradiated** [comment]
I've added support for exporting to Alacritty. The output looks like this:
https://github.com/stayradiated/termcolors/blob/master/examples/alacritty.txt

Adding support for importing shouldn't be too difficult, as you said, it's just YAML.

**Comment by stayradiated** [comment]
I've added support importing colors as well.
